// src/i18n.js

export const TRANSLATIONS = {
  en: {
    name: "English",
    menu: { start: "Start Game", hangar: "Hangar", leaderboard: "Leaderboard", options: "Options", bank: "BANK", highscore: "HIGH SCORE" },
    hud: { score: "SCORE", triple: "TRIPLE SHOT", combo: "COMBO" },
    pause: { title: "PAUSE", continue: "Continue", exit: "Exit to Menu" },
    options: { title: "OPTIONS", blur: "Motion Blur", music: "Music Volume", back: "Back", lang: "Language", fullscreen: "Fullscreen" }, // <--- ADICIONADO
    gameover: { title: "GAME OVER", score: "FINAL SCORE", scrap: "SCRAP COLLECTED", newRecord: "★ NEW HIGH SCORE! ★", retry: "Try Again", menu: "Main Menu", enterName: "ENTER NAME", submit: "SUBMIT SCORE", saved: "✔ SCORE SAVED!", lowScore: "⚠ DID NOT BEAT PERSONAL BEST", error: "❌ ERROR CONNECTING" },
    shop: { title: "HANGAR", credits: "CREDITS", back: "BACK", buy: "BUY", owned: "OWNED", activated: "ACTIVATED", notOwned: "NOT OWNED", level: "LEVEL", equip: "EQUIP", unequip: "DISABLE", statusOn: "ACTIVE", statusOff: "DISABLED", items: { lives: { title: "Hull Armor", desc: "+1 Max Life." }, autofire: { title: "Auto-Fire", desc: "Hold to shoot continuously." }, magnet: { title: "Global Magnet", desc: "Attracts loot from everywhere." }, ricochet: { title: "Ricochet", desc: "Shots bounce off walls." } } },
    leaderboard: { title: "GLOBAL RANKING", rank: "RANK", name: "PILOT", score: "SCORE", loading: "Loading Data..." }
  },
  pt: {
    name: "Português",
    menu: { start: "Iniciar Jogo", hangar: "Hangar", leaderboard: "Ranking", options: "Opções", bank: "BANCO", highscore: "RECORDE" },
    hud: { score: "PONTOS", triple: "TIRO TRIPLO", combo: "COMBO" },
    pause: { title: "PAUSA", continue: "Continuar", exit: "Sair para o Menu" },
    options: { title: "OPÇÕES", blur: "Desfoque", music: "Volume Música", back: "Voltar", lang: "Idioma", fullscreen: "Tela Cheia" }, // <--- ADICIONADO
    gameover: { title: "FIM DE JOGO", score: "PONTUAÇÃO", scrap: "SUCATA COLETADA", newRecord: "★ NOVO RECORDE! ★", retry: "Tentar de Novo", menu: "Menu Principal", enterName: "NOME DO PILOTO", submit: "ENVIAR RECORDE", saved: "✔ RECORDE GUARDADO!", lowScore: "⚠ NÃO BATESTE O TEU RECORDE", error: "❌ ERRO DE LIGAÇÃO" },
    shop: { title: "HANGAR", credits: "CRÉDITOS", back: "VOLTAR", buy: "COMPRAR", owned: "ADQUIRIDO", activated: "ATIVADO", notOwned: "NÃO POSSUI", level: "NÍVEL", equip: "EQUIPAR", unequip: "DESATIVAR", statusOn: "ATIVO", statusOff: "DESLIGADO", items: { lives: { title: "Blindagem", desc: "+1 Vida Máxima." }, autofire: { title: "Disparo Auto", desc: "Segure para atirar." }, magnet: { title: "Íman Global", desc: "Atrai tudo no ecrã." }, ricochet: { title: "Ricochete", desc: "Tiros saltam nas paredes." } } },
    leaderboard: { title: "RANKING GLOBAL", rank: "POS", name: "PILOTO", score: "PONTOS", loading: "A carregar..." }
  },
  fr: { name: "Français", menu: { start: "Commencer", hangar: "Hangar", leaderboard: "Classement", options: "Options", bank: "BANQUE", highscore: "RECORD" }, hud: { score: "SCORE", triple: "TIR TRIPLE", combo: "COMBO" }, pause: { title: "PAUSE", continue: "Continuer", exit: "Quitter" }, options: { title: "OPTIONS", blur: "Flou", music: "Volume Musique", back: "Retour", lang: "Langue", fullscreen: "Plein Écran" }, gameover: { title: "GAME OVER", score: "SCORE FINAL", scrap: "RÉCOLTÉ", newRecord: "★ NOUVEAU RECORD! ★", retry: "Rejouer", menu: "Menu Principal", enterName: "VOTRE NOM", submit: "ENVOYER", saved: "✔ SCORE ENREGISTRÉ !", lowScore: "⚠ RECORD NON BATTU", error: "❌ ERREUR DE CONNEXION" }, shop: { title: "HANGAR", credits: "CRÉDITS", back: "RETOUR", buy: "ACHETER", owned: "ACQUIS", activated: "ACTIVÉ", notOwned: "NON ACQUIS", level: "NIVEAU", equip: "ACTIVER", unequip: "DÉSACTIVER", statusOn: "ACTIF", statusOff: "INACTIF", items: { lives: { title: "Blindage", desc: "+1 Vie." }, autofire: { title: "Tir Auto", desc: "Maintenir pour tirer." }, magnet: { title: "Aimant Global", desc: "Attire tout." }, ricochet: { title: "Ricochet", desc: "Rebond sur les murs." } } }, leaderboard: { title: "CLASSEMENT", rank: "#", name: "PILOTE", score: "SCORE", loading: "Chargement..." } },
  de: { name: "Deutsch", menu: { start: "Starten", hangar: "Hangar", leaderboard: "Bestenliste", options: "Optionen", bank: "BANK", highscore: "REKORD" }, hud: { score: "PUNKTE", triple: "DREIFACHSCHUSS", combo: "COMBO" }, pause: { title: "PAUSE", continue: "Weiter", exit: "Beenden" }, options: { title: "OPTIONEN", blur: "Bewegungsunschärfe", music: "Musik", back: "Zurück", lang: "Sprache", fullscreen: "Vollbild" }, gameover: { title: "GAME OVER", score: "ERGEBNIS", scrap: "GESAMMELT", newRecord: "★ NEUER REKORD! ★", retry: "Nochmal", menu: "Hauptmenü", enterName: "NAME EINGEBEN", submit: "SENDEN", saved: "✔ PUNKTZAHL GESPEICHERT!", lowScore: "⚠ REKORD NICHT GEBROCHEN", error: "❌ VERBINDUNGSFEHLER" }, shop: { title: "HANGAR", credits: "GUTHABEN", back: "ZURÜCK", buy: "KAUFEN", owned: "GEKAUFT", activated: "AKTIV", notOwned: "NICHT GEKAUFT", level: "STUFE", equip: "AUSRÜSTEN", unequip: "DEAKTIVIEREN", statusOn: "AKTIV", statusOff: "INAKTIV", items: { lives: { title: "Panzerung", desc: "+1 Leben." }, autofire: { title: "Autofeuer", desc: "Halten zum Schießen." }, magnet: { title: "Globalmagnet", desc: "Zieht alles an." }, ricochet: { title: "Querschläger", desc: "Schüsse prallen ab." } } }, leaderboard: { title: "BESTENLISTE", rank: "RANG", name: "PILOT", score: "PUNKTE", loading: "Laden..." } },
  es: { name: "Español", menu: { start: "Empezar", hangar: "Hangar", leaderboard: "Clasificación", options: "Opciones", bank: "BANCO", highscore: "RÉCORD" }, hud: { score: "PUNTOS", triple: "DISPARO TRIPLE", combo: "COMBO" }, pause: { title: "PAUSA", continue: "Continuar", exit: "Salir" }, options: { title: "OPCIONES", blur: "Desenfoque", music: "Música", back: "Volver", lang: "Idioma", fullscreen: "Pantalla Completa" }, gameover: { title: "FIN DEL JUEGO", score: "PUNTUACIÓN", scrap: "RECOGIDO", newRecord: "★ ¡NUEVO RÉCORD! ★", retry: "Reintentar", menu: "Menú Principal", enterName: "NOMBRE", submit: "ENVIAR", saved: "✔ ¡PUNTUACIÓN GUARDADA!", lowScore: "⚠ NO SUPERASTE TU RÉCORD", error: "❌ ERROR DE CONEXIÓN" }, shop: { title: "HANGAR", credits: "CRÉDITOS", back: "VOLVER", buy: "COMPRAR", owned: "ADQUIRIDO", activated: "ACTIVADO", notOwned: "NO POSEÍDO", level: "NIVEL", equip: "EQUIPAR", unequip: "DESACTIVAR", statusOn: "ACTIVO", statusOff: "INACTIVO", items: { lives: { title: "Blindaje", desc: "+1 Vida." }, autofire: { title: "Disparo Auto", desc: "Mantener para disparar." }, magnet: { title: "Imán Global", desc: "Atrae todo." }, ricochet: { title: "Rebote", desc: "Rebota en paredes." } } }, leaderboard: { title: "CLASIFICACIÓN", rank: "POS", name: "PILOTO", score: "PUNTOS", loading: "Cargando..." } },
  it: { name: "Italiano", menu: { start: "Inizia", hangar: "Hangar", leaderboard: "Classifica", options: "Opzioni", bank: "BANCA", highscore: "RECORD" }, hud: { score: "PUNTI", triple: "COLPO TRIPLO", combo: "COMBO" }, pause: { title: "PAUSA", continue: "Continua", exit: "Esci" }, options: { title: "OPZIONI", blur: "Sfocatura", music: "Musica", back: "Indietro", lang: "Lingua", fullscreen: "Schermo Intero" }, gameover: { title: "GAME OVER", score: "PUNTEGGIO", scrap: "RACCOLTO", newRecord: "★ NUOVO RECORD! ★", retry: "Riprova", menu: "Menu Principale", enterName: "NOME", submit: "INVIA", saved: "✔ PUNTEGGIO SALVATO!", lowScore: "⚠ RECORD NON BATTUTO", error: "❌ ERRORE DI CONNESSIONE" }, shop: { title: "HANGAR", credits: "CREDITI", back: "INDIETRO", buy: "COMPRA", owned: "POSSEDUTO", activated: "ATTIVO", notOwned: "NON POSSEDUTO", level: "LIVELLO", equip: "EQUIPAGGIA", unequip: "DISABILITA", statusOn: "ATTIVO", statusOff: "INATTIVO", items: { lives: { title: "Corazza", desc: "+1 Vita." }, autofire: { title: "Fuoco Auto", desc: "Tieni premuto." }, magnet: { title: "Magnete", desc: "Attrae tutto." }, ricochet: { title: "Rimbalzo", desc: "Colpi rimbalzano." } } }, leaderboard: { title: "CLASSIFICA", rank: "POS", name: "PILOTA", score: "PUNTI", loading: "Caricamento..." } },
  ru: { name: "Русский", menu: { start: "Играть", hangar: "Ангар", leaderboard: "Рейтинг", options: "Опции", bank: "БАНК", highscore: "РЕКОРД" }, hud: { score: "СЧЕТ", triple: "ТРОЙНОЙ ВЫСТРЕЛ", combo: "COMBO" }, pause: { title: "ПАУЗА", continue: "Продолжить", exit: "Выход" }, options: { title: "ОПЦИИ", blur: "Размытие", music: "Музыка", back: "Назад", lang: "Язык", fullscreen: "На весь экран" }, gameover: { title: "КОНЕЦ ИГРЫ", score: "СЧЕТ", scrap: "СОБРАНО", newRecord: "★ НОВЫЙ РЕКОРД! ★", retry: "Повторить", menu: "Главное меню", enterName: "ИМЯ", submit: "ОТПРАВИТЬ", saved: "✔ СЧЕТ СОХРАНЕН!", lowScore: "⚠ НЕ ПОБИЛ РЕКОРД", error: "❌ ОШИБКА ПОДКЛЮЧЕНИЯ" }, shop: { title: "АНГАР", credits: "КРЕДИТЫ", back: "НАЗАД", buy: "КУПИТЬ", owned: "КУПЛЕНО", activated: "АКТИВНО", notOwned: "НЕТ", level: "УР.", equip: "ВКЛЮЧИТЬ", unequip: "ВЫКЛЮЧИТЬ", statusOn: "ВКЛ", statusOff: "ВЫКЛ", items: { lives: { title: "Броня", desc: "+1 Жизнь." }, autofire: { title: "Авто-огонь", desc: "Зажать для стрельбы." }, magnet: { title: "Магнит", desc: "Притягивает все." }, ricochet: { title: "Рикошет", desc: "Отскок от стен." } } }, leaderboard: { title: "РЕЙТИНГ", rank: "№", name: "ПИЛОТ", score: "СЧЕТ", loading: "Загрузка..." } },
  ar: { name: "العربية", menu: { start: "ابدأ اللعبة", hangar: "المتجر", leaderboard: "لوحة المتصدرين", options: "خيارات", bank: "الرصيد", highscore: "أعلى نتيجة" }, hud: { score: "النتيجة", triple: "إطلاق ثلاثي", combo: "COMBO" }, pause: { title: "توقف", continue: "استمرار", exit: "خروج" }, options: { title: "خيارات", blur: "ضبابية الحركة", music: "الموسيقى", back: "رجوع", lang: "اللغة", fullscreen: "ملء الشاشة" }, gameover: { title: "انتهت اللعبة", score: "النتيجة النهائية", scrap: "تم جمعها", newRecord: "★ رقم قياسي جديد! ★", retry: "حاول مرة أخرى", menu: "القائمة الرئيسية", enterName: "اسمك", submit: "إرسال", saved: "✔ تم حفظ النتيجة!", lowScore: "⚠ لم تحطم رقمك القياسي", error: "❌ خطأ في الاتصال" }, shop: { title: "المتجر", credits: "الرصيد", back: "رجوع", buy: "شراء", owned: "مملوك", activated: "مفعل", notOwned: "غير مملوك", level: "مستوى", equip: "تجهيز", unequip: "تعطيل", statusOn: "نشط", statusOff: "معطل", items: { lives: { title: "درع الهيكل", desc: "+1 حياة." }, autofire: { title: "إطلاق تلقائي", desc: "استمر بالضغط للإطلاق." }, magnet: { title: "مغناطيس شامل", desc: "يجذب كل شيء." }, ricochet: { title: "ارتداد", desc: "الطلقات ترتد." } } }, leaderboard: { title: "أفضل اللاعبين", rank: "#", name: "الطيار", score: "النتيجة", loading: "جار التحميل..." } },
  zh: { name: "中国人", menu: { start: "开始游戏", hangar: "机库", leaderboard: "排行榜", options: "选项", bank: "银行", highscore: "最高分" }, hud: { score: "分数", triple: "三连射", combo: "COMBO" }, pause: { title: "暂停", continue: "继续", exit: "退出" }, options: { title: "选项", blur: "动态模糊", music: "音乐音量", back: "返回", lang: "语言", fullscreen: "全屏" }, gameover: { title: "游戏结束", score: "最终分数", scrap: "收集碎片", newRecord: "★ 新纪录！ ★", retry: "重试", menu: "主菜单", enterName: "名字", submit: "提交", saved: "✔ 分数已保存！", lowScore: "⚠ 未打破最高纪录", error: "❌ 连接错误" }, shop: { title: "机库", credits: "信用点", back: "返回", buy: "购买", owned: "已拥有", activated: "已激活", notOwned: "未拥有", level: "等级", equip: "装备", unequip: "卸下", statusOn: "启用", statusOff: "禁用", items: { lives: { title: "船体装甲", desc: "+1 生命值。" }, autofire: { title: "自动射击", desc: "按住射击。" }, magnet: { title: "全局磁铁", desc: "吸引所有物品。" }, ricochet: { title: "跳弹", desc: "子弹反弹。" } } }, leaderboard: { title: "全球排名", rank: "排名", name: "飞行员", score: "分数", loading: "载入中..." } },
  ja: { name: "日本語", menu: { start: "ゲーム開始", hangar: "格納庫", leaderboard: "リーダーボード", options: "設定", bank: "銀行", highscore: "ハイスコア" }, hud: { score: "スコア", triple: "トリプルショット", combo: "COMBO" }, pause: { title: "一時停止", continue: "続ける", exit: "終了" }, options: { title: "設定", blur: "モーションブラー", music: "音楽", back: "戻る", lang: "言語", fullscreen: "フルスクリーン" }, gameover: { title: "ゲームオーバー", score: "スコア", scrap: "獲得スクラップ", newRecord: "★ 新記録！ ★", retry: "リトライ", menu: "メインメニュー", enterName: "名前", submit: "送信", saved: "✔ スコア保存完了！", lowScore: "⚠ 自己ベスト更新ならず", error: "❌ 接続エラー" }, shop: { title: "格納庫", credits: "クレジット", back: "戻る", buy: "購入", owned: "所持", activated: "有効", notOwned: "未所持", level: "LV", equip: "装備", unequip: "外す", statusOn: "有効", statusOff: "無効", items: { lives: { title: "装甲", desc: "+1 ライフ。" }, autofire: { title: "連射", desc: "押しっぱなしで発射。" }, magnet: { title: "グローバル磁石", desc: "全てを引き寄せる。" }, ricochet: { title: "跳弾", desc: "弾が反射する。" } } }, leaderboard: { title: "ランキング", rank: "順位", name: "パイロット", score: "スコア", loading: "読み込み中..." } }
};